export enum GameState {
  IDLE = 'IDLE',
  FISHING = 'FISHING',
  CATCHING = 'CATCHING',
  CAUGHT = 'CAUGHT',
  BOSS_ACTIVE = 'BOSS_ACTIVE',
  PENALTY = 'PENALTY',
}

export interface CatchResult {
  name: string;
  emoji: string;
  score: number;
  description?: string; // Generated by Gemini
  tier: 'normal' | 'rare' | 'bad';
}

export interface Station {
  id: string;
  name: string;
  x: number;
  y: number;
  isMine: boolean;
  avatarSeed: number;
}

export interface GestureState {
  isWaving: boolean;    // Open Palm (Fishing)
  isFist: boolean;      // Closed Fist (Catching)
  isPointing: boolean;  // Pointing Up (Moving)
  handPresent: boolean;
  move: { x: number; y: number }; // Joystick vector (-1 to 1)
}